package br.fatec.taroTI.entidades;

import java.util.Random;

public class Baralho {
    private final Carta[] cartas = {
            new Carta("Tolo", "Vai fundo, cara.", "Tu tá de meninagem!", "maior/00tolo"),
            new Carta("Mago", "O pai tá on!", "Temos um Xerox Rolmes.", "maior/01mago"),
            new Carta("Imperatriz",
                    "A mãe tá on!",
                    "Tá na hora de aprender a ir no banheiro sozinho.",
                    "maior/03imperatriz"),
            new Carta("Imperador",
                    "Tá comandando geral.",
                    "Vai com calma aí, Stalin.",
                    "maior/04imperador"),
            new Carta("Hierofante",
                    "Embrace tradition.",
                    "Reject modernity.",
                    "maior/05hierofante"),
            new Carta("Os enamorados",
                    "Ai que fofo, gente! O casal!",
                    "Gado d+",
                    "maior/06enamorados"),
            new Carta("O carro",
                    "Vai porra, continua, caralho, vai!",
                    "Andando você tá, mas pra onde?",
                    "maior/07carro"),
            new Carta("Justiça",
                    "Tá certinho mano, vai na tua q tá tranquilo.",
                    "Não tenho provas, mas tenho convicção.",
                    "maior/08justica"),
            new Carta("O Enforcado", "Abstrai...", "Abstraiu demais.", "maior/12enforcado"),
            new Carta("Morte", "Aí fudeu!", "Aí fudeu...", "maior/13morte"),
            new Carta(
                    "Temperança",
                    "Suave.",
                    "Esquece esse negócio de terceira via...",
                    "maior/14temperanca"),
            new Carta("Sol", "Vitória da razão.", "É muito Sol na cabeça...", "maior/19sol"),

            new Carta("II de Ouros", "Tá no corre.", "Dá seus pulo, cara.", "ouros/02"),
            new Carta("VI de Ouros",
                    "Não tem vergonha em pedir ajuda.",
                    "Tem que ajudar os outros também, ô vacilaum.",
                    "ouros/06"),
            new Carta("VIII de Ouros",
                    "Tá na hora de aprender algo novo.",
                    "Tá estagnado, confortável demais, cabou o tesão...",
                    "ouros/08"),
            new Carta("X de Ouros",
                    "Já pode aposentar.",
                    "Vô mentir pra vc não, velho. Tú tá é fudido, falido, mal pago...",
                    "ouros/10"),
            new Carta("Valete de Ouros",
                    "Tá fazendo meninagem com o seu dinheiro! Continue.",
                    "Tá fazendo meninagem com o seu dinheiro! Pare.",
                    "ouros/11"),
            new Carta("Cavaleiro de Ouros",
                    "Vai carpir um pasto q você ganha mais.",
                    "Se cair de quatro não levanta mais.",
                    "ouros/12"),

            new Carta("Às de Paus",
                    "Tá criando várias paradas.",
                    "Relaxa aí ô Artistão.",
                    "paus/01"),
            new Carta("III de Paus",
                    "O início de um sonho.",
                    "Deu tudo errado.",
                    "paus/03"),
            new Carta("IV de Paus",
                    "Sextou!",
                    "Essa festa virou enterro...",
                    "paus/04"),
            new Carta("VII de Paus",
                    "Ilusão & desilusão.",
                    "Hesitação & Revés.",
                    "paus/07"),
            new Carta("IX de Paus", "Depressão.", "Depressão pra caralho!", "paus/09"),
            new Carta("X de Paus",
                    "Pode delegar q tá tranquilo.",
                    "Deixa os outros fazerem também, ô fominha.",
                    "paus/10"),

            new Carta("Às de Copos", "Vai começar o amor.", "Vai começar de cafonice.", "copos/01"),
            new Carta("II de Copos", "Vai achar alguém.", "Vai perder alguém.", "copos/02"),
            new Carta("V de Copos",
                    "Perda",
                    "Aceitação",
                    "copos/05"),
            new Carta("VII de Copos",
                    "Parece que vai dar tudo certo. Parece...",
                    "Investiu em bitcoin?",
                    "copos/07"),
            new Carta("Valete de Copos",
                    "Olha que cristalzinho puro.",
                    "Deixa de ser criança, criança.",
                    "copos/11"),
            new Carta("Cavaleiro de Copos",
                    "Quase um príncipe encantado.",
                    "Deixa de ser diva, flor.",
                    "copos/12"),
            new Carta("Rainha de Copos",
                    "Emoções são demais!",
                    "São emoções demais...",
                    "copos/13"),
            new Carta("Rei de Copos",
                    "Manja das emoções.",
                    "Tá viajando demais nas emoções.",
                    "copos/14"),

            new Carta("III de Espadas",
                    "Solidão, rejeição, fossa ...",
                    "Recuperação, aproveita o descanso.",
                    "espadas/03"),
            new Carta("VI de Espadas",
                    "Mudança pesada à frente.",
                    "Babagem pesada pra carregar.",
                    "espadas/06"),
            new Carta("VII de Espadas",
                    "Tem que manter isso aí!",
                    "Vai perder tudo que ganhou.",
                    "espadas/07"),
            new Carta("Valete de Espadas",
                    "Vai na fé leske!",
                    "Deixa disso meu jovem mancebo.",
                    "espadas/11"),
            new Carta("Cavaleiro de Espadas",
                    "Tá playboy",
                    "Foco jovem, foco!",
                    "espadas/12"),
            new Carta("Rainha de Espadas",
                    "Slay it, quinn",
                    "Calma, porra! Calma, caralho!",
                    "espadas/13")
    };

    public Baralho() {

    }

    public Carta getLeitura() {
        int i = new Random().nextInt(cartas.length);
        Carta temp = cartas[i];
        temp.setDirecao();
        return temp;
    }
}
