package br.fatec.taroTI.entidades;

import java.util.Random;

public class Baralho {
    private final Carta[] cartas = {
            new Carta("Tolo", 0,
                    0,
                    "Vai fundo, cara.",
                    "Tu tá de meninagem!"),
            new Carta("Mago", 1,
                    0,
                    "O pai tá on!",
                    "Temos um Xerox Rolmes."),
            new Carta("Imperatriz",3,
                    0,
                    "A mãe tá on!",
                    "Tá na hora de aprender a ir no banheiro sozinho."),
            new Carta("Imperador",4,
                    0,
                    "Tá comandando geral.",
                    "Vai com calma aí, Stalin."),
            new Carta("Hierofante",5,
                    0,
                    "Embrace tradition.",
                    "Reject modernity."),
            new Carta("Os enamorados",6,
                    0,
                    "Ai que fofo, gente! O casal!",
                    "Gado d+"),
            new Carta("O carro",7,
                    0,
                    "Vai porra, continua, caralho, vai!",
                    "Andando você tá, mas pra onde?"),
            new Carta("Justiça",8,
                    0,
                    "Tá certinho mano, vai na tua q tá tranquilo.",
                    "Não tenho provas, mas tenho convicção."),
            new Carta("O Enforcado",12,
                    0,
                    "Abstrai...",
                    "Abstraiu demais."),
            new Carta("Morte",13,
                    0,
                    "Aí fudeu!",
                    "Aí fudeu..."),
            new Carta("Temperança",14,
                    0,
                    "Suave.",
                    "Esquece esse negócio de terceira via..."),
            new Carta("Sol",19,
                    0,
                    "Vitória da razão.",
                    "É muito Sol na cabeça..."),

            new Carta("II", 2,
                    1,
                    "Tá no corre.",
                    "Dá seus pulo, cara."),
            new Carta("VI", 6,
                    1,
                    "Não tem vergonha em pedir ajuda.",
                    "Tem que ajudar os outros também, ô vacilaum."),
            new Carta("VIII", 8,
                    1,
                    "Tá na hora de aprender algo novo.",
                    "Tá estagnado, confortável demais, cabou o tesão..."),
            new Carta("X", 10,
                    1,
                    "Já pode aposentar.",
                    "Vô mentir pra vc não, velho. Tú tá é fudido, falido, mal pago..."),
            new Carta("Estagiário", 11,
                    1,
                    "Tá fazendo meninagem com o seu dinheiro! Continue.",
                    "Tá fazendo meninagem com o seu dinheiro! Pare."),
            new Carta("Júnior", 12,
                    1,
                    "Vai carpir um pasto q você ganha mais.",
                    "Se cair de quatro não levanta mais."),

            new Carta("Às", 1,
                    2,
                    "Tá criando várias paradas.",
                    "Relaxa aí ô Artistão."),
            new Carta("III",3,
                    2,
                    "O início de um sonho.",
                    "Deu tudo errado."),
            new Carta("IV", 4,
                    2,
                    "Sextou!",
                    "Essa festa virou enterro..."),
            new Carta("VII", 7,
                    2,
                    "Ilusão & desilusão.",
                    "Hesitação & Revés."),
            new Carta("IX",9,
                    2,
                    "Depressão.",
                    "Depressão pra caralho!"),
            new Carta("X",10,
                    2,
                    "Pode delegar q tá tranquilo.",
                    "Deixa os outros fazerem também, ô fominha."),

            new Carta("Às",1,
                    3,
                    "Vai começar o amor.",
                    "Vai começar de cafonice."),
            new Carta("II",2,
                    3,
                    "Vai achar alguém.",
                    "Vai perder alguém."),
            new Carta("V",5,
                    3,
                    "Perda",
                    "Aceitação"),
            new Carta("VII",7,
                    3,
                    "Parece que vai dar tudo certo. Parece...",
                    "Investiu em bitcoin?"),
            new Carta("IX",9,
                    3,
                    "Tá mimado d+.",
                    "Ué, mas não eram dez copos?"),
            new Carta("Estagiário",11,
                    3,
                    "Olha que cristalzinho puro.",
                    "Deixa de ser criança, criança."),
            new Carta("Júnior",12,
                    3,
                    "Quase um príncipe encantado.",
                    "Deixa de ser diva, flor."),
            new Carta("Pleno", 13,
                    3,
                    "Emoções são demais!",
                    "São emoções demais..."),
            new Carta("Sênior",14,
                    3,
                    "Manja das emoções.",
                    "Tá viajando demais nas emoções."),

            new Carta("III",3,
                    4,
                    "Solidão, rejeição, fossa ...",
                    "Recuperação, aproveita o descanso."),
            new Carta("VI", 6,
                    4,
                    "Mudança pesada à frente.",
                    "Babagem pesada pra carregar."),
            new Carta("VII", 7,
                    4,
                    "Tem que manter isso aí!",
                    "Vai perder tudo que ganhou."),
            new Carta("Estagiário", 11,
                    4,
                    "Vai na fé leske!",
                    "Deixa disso meu jovem mancebo."),
            new Carta("Júnior", 12,
                    4,
                    "Tá playboy",
                    "Foco jovem, foco!"),
            new Carta("Pleno", 13,
                    4,
                    "Slay it, quinn.",
                    "Calma, porra! Calma, caralho!"),
            new Carta("Sênior", 14,
                    4,
                    "O rei da porra.",
                    "Para de pagar de cuzão.")
    };

    public Baralho() {

    }

    public Carta getLeitura() {
        int i = new Random().nextInt(cartas.length);
        Carta temp = cartas[i];
        temp.setDirecao();
        return temp;
    }
}
