spring.datasource.url=jdbc:postgresql://localhost:5432/taroti
spring.datasource.username=usuario
spring.datasource.password=senha
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.flyway.enabled=true
spring.flyway.locations=classpath:migrations

server.port=8090

logging.file.name=logs/leituras.log
logging.file.path=logs
