create table if not exists carta (
	id bigserial not null,
	valor int4,
	naipe varchar(16) not null,
	descricao_certa TEXT,
	descricao_torta TEXT,
	primary key (id)
);

insert into carta (valor, naipe, descricao_certa, descricao_torta) values
	(0, 'PAUS', 'É o Ás de paus, ué', 'É o Ás de paus, só que de cabeça pra baixo'),
	(0, 'OUROS', 'É o Ás de ouros, ué', 'É o Ás de ouros, só que de cabeça pra baixo'),
	(0, 'ESPADAS', 'É o Ás de espadas, ué', 'É o Ás de espadas, só que de cabeça pra baixo'),
	(0, 'COPAS', 'É o Ás de copos, ué', 'É o Ás de copos, só que de cabeça pra baixo'),
	(1, 'PAUS', 'É o Ás de paus, ué', 'É o Ás de paus, só que de cabeça pra baixo'),
    (1, 'OUROS', 'É o Ás de ouros, ué', 'É o Ás de ouros, só que de cabeça pra baixo'),
    (1, 'ESPADAS', 'É o Ás de espadas, ué', 'É o Ás de espadas, só que de cabeça pra baixo'),
    (1, 'COPAS', 'É o Ás de copos, ué', 'É o Ás de copos, só que de cabeça pra baixo'),
    (2, 'PAUS', 'É o Ás de paus, ué', 'É o Ás de paus, só que de cabeça pra baixo'),
    (2, 'OUROS', 'É o Ás de ouros, ué', 'É o Ás de ouros, só que de cabeça pra baixo'),
    (2, 'ESPADAS', 'É o Ás de espadas, ué', 'É o Ás de espadas, só que de cabeça pra baixo'),
    (2, 'COPAS', 'É o Ás de copos, ué', 'É o Ás de copos, só que de cabeça pra baixo'),
    (3, 'PAUS', 'É o Ás de paus, ué', 'É o Ás de paus, só que de cabeça pra baixo'),
    (3, 'OUROS', 'É o Ás de ouros, ué', 'É o Ás de ouros, só que de cabeça pra baixo'),
    (3, 'ESPADAS', 'É o Ás de espadas, ué', 'É o Ás de espadas, só que de cabeça pra baixo'),
    (3, 'COPAS', 'É o Ás de copos, ué', 'É o Ás de copos, só que de cabeça pra baixo'),
    (4, 'PAUS', 'É o Ás de paus, ué', 'É o Ás de paus, só que de cabeça pra baixo'),
    (4, 'OUROS', 'É o Ás de ouros, ué', 'É o Ás de ouros, só que de cabeça pra baixo'),
    (4, 'ESPADAS', 'É o Ás de espadas, ué', 'É o Ás de espadas, só que de cabeça pra baixo'),
    (4, 'COPAS', 'É o Ás de copos, ué', 'É o Ás de copos, só que de cabeça pra baixo'),
    (5, 'PAUS', 'É o Ás de paus, ué', 'É o Ás de paus, só que de cabeça pra baixo'),
    (5, 'OUROS', 'É o Ás de ouros, ué', 'É o Ás de ouros, só que de cabeça pra baixo'),
    (5, 'ESPADAS', 'É o Ás de espadas, ué', 'É o Ás de espadas, só que de cabeça pra baixo'),
    (5, 'COPAS', 'É o Ás de copos, ué', 'É o Ás de copos, só que de cabeça pra baixo'),
    (6, 'PAUS', 'É o Ás de paus, ué', 'É o Ás de paus, só que de cabeça pra baixo'),
    (6, 'OUROS', 'É o Ás de ouros, ué', 'É o Ás de ouros, só que de cabeça pra baixo'),
    (6, 'ESPADAS', 'É o Ás de espadas, ué', 'É o Ás de espadas, só que de cabeça pra baixo'),
    (6, 'COPAS', 'É o Ás de copos, ué', 'É o Ás de copos, só que de cabeça pra baixo'),
    (7, 'PAUS', 'É o Ás de paus, ué', 'É o Ás de paus, só que de cabeça pra baixo'),
    (7, 'OUROS', 'É o Ás de ouros, ué', 'É o Ás de ouros, só que de cabeça pra baixo'),
   	(7, 'ESPADAS', 'É o Ás de espadas, ué', 'É o Ás de espadas, só que de cabeça pra baixo'),
   	(7, 'COPAS', 'É o Ás de copos, ué', 'É o Ás de copos, só que de cabeça pra baixo'),
   	(8, 'PAUS', 'É o Ás de paus, ué', 'É o Ás de paus, só que de cabeça pra baixo'),
  	(8, 'OUROS', 'É o Ás de ouros, ué', 'É o Ás de ouros, só que de cabeça pra baixo'),
   	(8, 'ESPADAS', 'É o Ás de espadas, ué', 'É o Ás de espadas, só que de cabeça pra baixo'),
   	(8, 'COPAS', 'É o Ás de copos, ué', 'É o Ás de copos, só que de cabeça pra baixo'),
   	(9, 'PAUS', 'É o Ás de paus, ué', 'É o Ás de paus, só que de cabeça pra baixo'),
   	(9, 'OUROS', 'É o Ás de ouros, ué', 'É o Ás de ouros, só que de cabeça pra baixo'),
  	(9, 'ESPADAS', 'É o Ás de espadas, ué', 'É o Ás de espadas, só que de cabeça pra baixo'),
   	(9, 'COPAS', 'É o Ás de copos, ué', 'É o Ás de copos, só que de cabeça pra baixo'),
  	(10, 'PAUS', 'É o Ás de paus, ué', 'É o Ás de paus, só que de cabeça pra baixo'),
   	(10, 'OUROS', 'É o Ás de ouros, ué', 'É o Ás de ouros, só que de cabeça pra baixo'),
    (10, 'ESPADAS', 'É o Ás de espadas, ué', 'É o Ás de espadas, só que de cabeça pra baixo'),
   	(10, 'COPAS', 'É o Ás de copos, ué', 'É o Ás de copos, só que de cabeça pra baixo'),
 	(11, 'PAUS', 'É o Ás de paus, ué', 'É o Ás de paus, só que de cabeça pra baixo'),
   	(11, 'OUROS', 'É o Ás de ouros, ué', 'É o Ás de ouros, só que de cabeça pra baixo'),
  	(11, 'ESPADAS', 'É o Ás de espadas, ué', 'É o Ás de espadas, só que de cabeça pra baixo'),
	(11, 'COPAS', 'É o Ás de copos, ué', 'É o Ás de copos, só que de cabeça pra baixo'),
	(12, 'PAUS', 'É o Ás de paus, ué', 'É o Ás de paus, só que de cabeça pra baixo'),
  	(12, 'OUROS', 'É o Ás de ouros, ué', 'É o Ás de ouros, só que de cabeça pra baixo'),
  	(12, 'ESPADAS', 'É o Ás de espadas, ué', 'É o Ás de espadas, só que de cabeça pra baixo'),
 	(12, 'COPAS', 'É o Ás de copos, ué', 'É o Ás de copos, só que de cabeça pra baixo'),
	(13, 'MAIOR', 'É muito eu', 'É um troxa mesmo'),
	(14, 'MAIOR', 'É muito eu', 'É um troxa mesmo'),
	(15, 'MAIOR', 'É muito eu', 'É um troxa mesmo'),
	(16, 'MAIOR', 'É muito eu', 'É um troxa mesmo'),
	(17, 'MAIOR', 'É muito eu', 'É um troxa mesmo'),
	(18, 'MAIOR', 'É muito eu', 'É um troxa mesmo'),
	(19, 'MAIOR', 'É muito eu', 'É um troxa mesmo'),
	(20, 'MAIOR', 'É muito eu', 'É um troxa mesmo'),
	(21, 'MAIOR', 'É muito eu', 'É um troxa mesmo'),
	(22, 'MAIOR', 'É muito eu', 'É um troxa mesmo'),
	(23, 'MAIOR', 'É muito eu', 'É um troxa mesmo'),
	(24, 'MAIOR', 'É muito eu', 'É um troxa mesmo'),
	(25, 'MAIOR', 'É muito eu', 'É um troxa mesmo'),
	(26, 'MAIOR', 'É muito eu', 'É um troxa mesmo'),
	(27, 'MAIOR', 'É muito eu', 'É um troxa mesmo'),
	(28, 'MAIOR', 'É muito eu', 'É um troxa mesmo'),
	(29, 'MAIOR', 'É muito eu', 'É um troxa mesmo'),
	(30, 'MAIOR', 'É muito eu', 'É um troxa mesmo'),
	(31, 'MAIOR', 'É muito eu', 'É um troxa mesmo'),
	(32, 'MAIOR', 'É muito eu', 'É um troxa mesmo'),
	(33, 'MAIOR', 'É muito eu', 'É um troxa mesmo'),
	(34, 'MAIOR', 'É muito eu', 'É um troxa mesmo')
;