create table if not exists carta (
	id bigserial not null,
	valor int4,
	naipe varchar(16) not null,
	descricao_certa TEXT,
	descricao_torta TEXT,
	primary key (id)
);

insert into carta (valor, naipe, descricao_certa, descricao_torta) values
	(1, 'PAUS', 'Novos projetos', 'inspiração, começo'),
	(2, 'PAUS', 'Inquietação', 'decisões, panejar'),
	(3, 'PAUS', 'Estabelecer força', 'ação criativa, empreendimento'),
	(4, 'PAUS', 'Harmonia', 'celebração, casamento'),
	(5, 'PAUS', 'Luta, Conflito', 'competição, tensão'),
	(6, 'PAUS', 'Vitoria', 'auto confiança, reconhecimento'),
	(7, 'PAUS', 'Obstaculos', 'desafio, perseverança'),
	(8, 'PAUS', 'Atividade', 'viagem, mudança rapida'),
	(9, 'PAUS', 'Recuperação', 'persistencia, teste de fé'),
	(10, 'PAUS', 'Fardo, Peso', 'stress, responsabilidade'),
	(11, 'PAUS', 'Mensagem', 'entusiamo, descobrimento,'),
	(12, 'PAUS', 'Movimento', 'aventura, luxúria'),
	(13, 'PAUS', 'Criação', 'determinação, exuberancia'),
	(14, 'PAUS', 'Lider', 'empresario, líder'),
	(1, 'COPAS', 'Novos relacionamentos', 'romance, amizade,'),
	(2, 'COPAS', 'Parceria', 'atração profunda, conexão'),
	(3, 'COPAS', 'Celebração', 'celebração em geral'),
	(4, 'COPAS', 'Insatisfação', 'enstrospeção, apatia'),
	(5, 'COPAS', 'Arrependimento', 'desespero, perda'),
	(6, 'COPAS', 'Melancolia', 'recuperar, memorias'),
	(7, 'COPAS', 'Escolhas', 'ilusão, fantasia'),
	(8, 'COPAS', 'Nova direção', 'desapontado, desilisão'),
	(9, 'COPAS', 'Satisfação', 'prazer, alegria'),
	(10, 'COPAS', 'Felicidade', 'alegria, familia'),
	(11, 'COPAS', 'Mensageiro', 'sonhador, sensível'),
	(12, 'COPAS', 'Movimento', 'romantico, encantador'),
	(13, 'COPAS', 'Influenciar', 'calma, compaixão'),
	(14, 'COPAS', 'Autoridade', 'emocionalmente equilibrado'),
	(1, 'ESPADAS', 'Algo chegando', 'operações, excessos'),
	(2, 'ESPADAS', 'Escolhas', 'indecisão, impasse'),
	(3, 'ESPADAS', 'Coração partido', 'separação, infidelidade,'),
	(4, 'ESPADAS', 'Descansar', 'solidão, dor'),
	(5, 'ESPADAS', 'Derrota', 'fracasso, perda'),
	(6, 'ESPADAS', 'Progresso', 'transição, deixar para tras'),
	(7, 'ESPADAS', 'Traição', 'decepção, mentiras'),
	(8, 'ESPADAS', 'Restrição', 'mas noticias, calúnias'),
	(9, 'ESPADAS', 'Depressão', 'ansiedade, angústia'),
	(10, 'ESPADAS', 'Infortuno', 'desistir, martírio'),
	(11, 'ESPADAS', 'Joven', 'curioso, energetico'),
	(12, 'ESPADAS', 'Agressivo', 'confiança, determinação'),
	(13, 'ESPADAS', 'Vingativa', 'independente, direta'),
	(14, 'ESPADAS', 'Homem lógico', 'intelectual, sabio'),
	(1, 'OUROS', 'Potencial', 'prosperidade, sucesso'),
    (2, 'OUROS', 'Dualidade', 'adaptação, balanço'),
    (3, 'OUROS', 'Comunicação', 'colaboração, trabalho em equipe'),
    (4, 'OUROS', 'Estabilidade', 'estabilidade, segurança'),
    (5, 'OUROS', 'Adversidade', 'pobreza, insegurança'),
    (6, 'OUROS', 'Crescimento', 'caridade, generosidade'),
    (7, 'OUROS', 'Fé', 'investimento, visão'),
    (8, 'OUROS', 'Mudança', 'educação, engajamento'),
  	(9, 'OUROS', 'Processo', 'gratidão, luxúria'),
   	(10, 'OUROS', 'Conclusão', 'estabelecimento, riqueza'),
   	(11, 'OUROS', 'Mensagem', 'novos negocios, manifestação'),
   	(12, 'OUROS', 'Movimento', 'eficiencia, mensagem'),
  	(13, 'OUROS', 'Influencia', 'pés no chão, maternal'),
    (14, 'OUROS', 'Autoridade', 'controlar, disciplina'),
	(0, 'MAIOR', 'Viagem, liberdade, inocencia', 'imaturidade, mentiroso, sem rumo'),
	(1, 'MAIOR', '	Ação, Novidades, poder', 'manipulador, trapaceiro, mau planejamento'),
	(2, 'MAIOR', 'Sabedoria, misterio, oculto', 'falsidade, segredos, amantes'),
	(3, 'MAIOR', 'Comunicação, fertilidade, realizações', 'excesso de vaidade, controladora'),
	(4, 'MAIOR', 'Proteção, segurança, estabilidade', 'centralizador, inflexível, teimoso'),
	(5, 'MAIOR', 'Aconselhamento, estudos, tradição', 'preconceitos, tabus, rigidez'),
	(6, 'MAIOR', 'Escolhas, relacionamentos, amor', 'duvidas, decisões, dualidade'),
	(7, 'MAIOR', 'Controle, rumo, oportunidades', 'mudanças rápidas, falta de controle, oposição'),
	(8, 'MAIOR', 'Sensualidade, coragem, autocontrole', 'recuar, falta de autocontrole, emoção bruta'),
	(9, 'MAIOR', 'Reclusão, paciência, estudos', 'solidão, avareza, isolamento'),
	(10, 'MAIOR', 'Viagem, mudança inesperada, destino', 'instabilidade, perder controle, azar'),
	(11, 'MAIOR', 'Negociações legais, reconciliação, ser justo', 'frieza, ser injusto, desonestidade'),
	(12, 'MAIOR', 'Estagnação, sacrifício, deixar ir', 'jogos, estagnação, indecisão'),
	(13, 'MAIOR', 'Transformação, mudança, fim de ciclo', 'perdas, destruição, resistência à mudança'),
	(14, 'MAIOR', 'Equilibrio, harmonia, moderação', 'lentidão, paciência, desequilibrio'),
	(15, 'MAIOR', 'Tentação, material, sexualidade', 'vícios, obsessões, falta de controle'),
	(16, 'MAIOR', 'Ruptura, perda, destruição', 'reconstrução, adiar o inevitável, trauma'),
	(17, 'MAIOR', 'Esperança, inspiração, espiritualidade', 'ingenuidade, má fé, desanimo'),
	(18, 'MAIOR', 'Ilusão, duvidas, fertilidade', 'traição, decepção, medos'),
	(19, 'MAIOR', 'Alegria, realizações, gravidez', 'tristeza, insatisfação, desmotivar'),
	(20, 'MAIOR', 'Renovação, Renascimento, resgate', 'ciclo vicioso, esperar por ajuda divina'),
	(21, 'MAIOR', 'Viagem, sucesso, conclusão', 'estagnação, planos fracassados, fim de ciclo')
;